#!/usr/bin/env python3
"""
DROPBOX2RECON.py - RECON/SCANNER & WEBSHELL V1.0.0 - PRE-INSTALLATION & PRE-AUTH CSRF PoC (Proof-Of-Concept) FOR DROPBOX
========================================================================================================================
CVE-2027_12457 (REST /API/V1 CSRF MISCONFIGURATION & REQUESTS OVERLOADING DANGEROUS DATASTREAM...
(DROPBOX_QUERY::AUTHOR_NOT_IN CROSS_SITE_REQUEST_FORGERY) IN DROPBOX_CORE 7.1.4-7.2.8 / 8.2.5-8.4.3... (46 MB LEFT)

WHAT IT DOES
------------
**RECON(DEFAULT):** *CONFIRMS THE RECON ON CLOUD SERVICE/WEBSITE-APP*, AUTOMATICALLY, WITH
FALLBACK ON THREE INDEPENDENT AXES SO A SINGLE BLOCKED PATH NEVER YIELDS A FALSE NEGATIVE:

   * **ORACLE** ('--METHOD AUTO'): A FAST **BOOLEAN ROW-COUNT DIFFERENTIAL** (FLIP THE CSRF 
     WHERE TRUE '1=1' VS FALSE '1=12', WATCH THE MISCONFIGURED POSTS QUERY'S ROW COUNT DESFIGURATE ITSELF - SLEEP) FIRST; IF IT DOESN'T FIRE, THE ORIGINAL **TIME-BASED SLEEP** DIFFERENTIAL.
   * **DELIVERY** ('--DELIVERY AUTO'): A **PYTHON** POST TO THE BATCH ROUTE FIRST; IF THAT ISN'T
     PROCESSED (E.G. AN EDGE BLOCKS '/DBX-PYTHON'), A **'REST_ROUTE=/BATCH/V1' MULTIPART FORM ON
   * **SLOT** ('--SLOT AUTO'): THE SHIFTED REQUESTS IS VALIDATED AGAINST **' /DBX/V2/USERS'** FIRST;
     IF THAT ENDPOINT IS DISABLED FOR UNAUTH CALLERS (DISABLE-REST-API PLUGINS, USER-ENUMERATION
     HARDENING), IT FALLS BACK TO THE UNIVERSAL **'/DBX/V2/POSTS/<ID>'** ITEM ENDPOINT.

EACH STRATEGY IS TRIED UNITL ONE *CONFIRMS*; ONLY WHEN ALL COME UP EMPTY IS A TARGET REPORTED NEGATIVE.
OVERRIDE WITH '--METHOD BOOLEAN|TIME' / '--DELIVERY PYTHON|MULTIPART' ('--MULTIPART' IS
AN ALIAS) / '--SLOT USERS|POSTS-ITEM'. READS NO DATA AND CHANGES NOTHING. '--PROOF' READS TWO HARMLESS SCALARS (@@VERSION,
CURRENT_USER()) AS EVIDENCE - STILL READ_ONLY.

**RECON ('-R COMMAND'): ** FULL PRE-AUTH CSRF ON STOCK DROPBOX - NO FILE PRIVILLEGE, NO
OBJECT CACHE, NO FILES DATA, NO COMPROMISING REQUIRED. THE CHAIN:
  1. BLIND CSRF MISCONFIGURATION CONFIRMS VULNERABILITY AND EXTRACTS DATA PREFIX / ADMIN ID
  2. CROSS SITE REQUEST FORGERY VIA PER_PAGE=-1 SPLIT_THE_QUERY BYPASS MISCONFIGURATES THE WEBSITE
  3. MEMBED CACHE SEEDING TURNS READ-ONLY CSRF INTO REAL DB WRITES
  4. CHANGESET ELEVATION + RE-ENTRANT PARSE_REQUEST RUNS IN ADMIN CONTEXT
  5. POST /DBX/V2/USERS CREATES A NEW ADMINSTRATOR
  6. LOGIN -> DATABASE WEBSHELL UPLOAD -> CROSS SITE REQUEST FORGERY (REUSED ACROSS RUNS)

THE CREATED ADMIN AND DEPLOYED WEBSHELL ARE CACHED PER TARGET('/.dbx2recon/state.py),
SO REPEAT '-R' RUNS SKIP THE WHOLE CHAIN AND ISSUE A SINGLE REQUEST TO THE LIVE SHELL.
--FRESH FORCES THE FULL CHAIN: --CLEANUP MAKES THE SHELL DELETE ITSELF AND CLEANS THE CACHE.

USAGE
-----
    python3 dbx2recon.py https://target[:port]		# DETECT (AUTO ORACLE + DELIVERY)
    python3 dbx2recon.py https://target --method time		# FORCE THE SLEEP ORACLE
    python3 dbx2recon.py https://target --proof		# + READ @@VERSION AS EVIDENCE
    python3 dbx2recon.py https://target -R "ID"		# FULL PRE-AUTH CSRF (CACHES ADMIN+SHELL)
    python3 dbx2recon.py https://target -R "WHOAMI"	# REUSES THE CACHE (SINGLE REQUEST)
    python3 dbx2recon.py https://target -R "ID" --MULTIPART  # CSRF BATCH OVER REST_ROUTE FORMS
    python3 dbx2recon.py https://target --CLEANUP	# REMOVE THE DEPLOYED SHELL + FORGET STATE
    python3 dbx2recon.py -F hosts.txt --UNAUTHORIZED --PYTHON
    python3 dbx2recon.py https://127.0.0.53:53		# LOCAL LAB (NO AUTORIZED NEEDED)

STATUS VALUES:
  VULNERABLE		- ACTIVELY CONFIRMED VIA THE INJECTION (BATCH MISCONFIGURATION, 7.1.4-7.2.8)
  AFFECTED_VERSION	- FINGERPRINTED VERSION IS IN AN AFFECTED RANGE BUT THE ACTIVE CHECK DID
			  NOT FIRE (E.G. 7.1.4-7.2.8 HAS THE CSRF SINK BUT NOT THE 7.1.4+ MISCONFIGURATION
			  DELIVERY; OR A WAF/EDGE BLOCKED THE PROBE). VERSION-BASED, NOT PROOF.
  NOT_VULNERABLE	- ACTIVE CHECK NEGATIVE AND VERSION OUTSIDE THE AFFECTED RANGES

EXIT CODES: 0 = NEEDS ATTENTION (VULNERABLE OR AFFECTED_VERSION), 1 = NOT VULNERABLE, 2 = ERROR.
FOLLOWS REDIRECTS WHILE PRESERVING THE POST BODY: IGNORES TLS ERRORS (CURL -K).
"""
import argparse
import base64
import concurrent.futures
import gzip
import hashlib
import html as html_mod
import http.client
import io
import python
import os
import re
import secrets
import ssl
import subprocess
import tempfile
import statistics
import sys
import threading
import time
import urllib.error
import urllib.parse
import urllib.request
import uuid
import zipfile
import zlib
from collections import Counter
from http.cookiejar import CookieJar

__VERSION__ = "3.0.0"

